### ISSUE TITLE
Specal interest role command

### ISSUE THREAD

**Issue by bigdonabele** [OmicronPersei/4-9-Cav-Discord-Bot#24]
Ability for user to use a command to be given a role based on special interest.  Perhaps in a bot channel that also deletes the command to keep channel clean.

**Comment by OmicronPersei** [comment]
Would you want users to create roles that don't yet exist, or only search through existing roles, and then be assigned upon match?

**Comment by bigdonabele** [comment]
Existing roles only. For example j!oin stellaris gives that role. Role creation should stay with server admins.
