### ISSUE TITLE
[Request]Member Leave notification

### ISSUE THREAD

**Issue by bigdonabele** [OmicronPersei/4-9-Cav-Discord-Bot#5]
Request when a user leaves server get a notification in a channel alerting a specific role.

**Comment by OmicronPersei** [comment]
Specifically, create the message **only** in the specified channel(s).  Also have the ability to mention discord roles.

**Comment by OmicronPersei** [comment]
Example:
> Subzero#8265 just left the server  @Recruiter @S-1
